import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HssNav from "@/components/HssNav";
import ScoutNav from "@/components/ScoutNav";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <div>
          <header className="flex flex-row justify-between bg-hss-scout-darkblue text-white">
            <p>Scout Logo placement</p>
            <ScoutNav />
          </header>
          <header className="flex flex-row justify-between items-center bg-hss-mediumblue text-white rounded-b-3xl">
            <div className="flex flex-row items-center">
              <a href="/" className="p-0"><img src="/LoggaHSSfärgmörkbakgrund.png" alt="Hss logga för mörk bakgrund" className="w-30 py-4.5 px-3.5" /></a>

              <img src="/HasselbyStrands-sjoscoutkar-vit.png" alt="HSS logga text till mörk bakgrund" className="w-full h-10" />
            </div>
            <HssNav />
          </header>
        </div>
        {children}
      </body>
    </html>
  );
}
