import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HssNav from "@/components/HssNav";
import ScoutNav from "@/components/ScoutNav";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <div>
          <header className="flex flex-row justify-between bg-hss-scout-darkblue text-white">
            <p>Scout Logo placement</p>
            <ScoutNav />
          </header>
          <header className="flex flex-row justify-between bg-hss-mediumblue text-white">
            <p>HSS Logo placement</p>
            <HssNav />
          </header>
        </div>
        {children}
      </body>
    </html>
  );
}
